# Application Settings
framework_name: 'Framework Name' # String: Framework name used in comment titles and json_metadata
community_name: 'Community Name' # String: Community name added to json_metadata
framework_beneficiary_enabled: false # Boolean: If enabled will add beneficiary to attribution comments
framework_beneficiary: '' # String: Beneficiary account added to attribution comments
default_posting_tags: ['steem-bot-framework','made-by-netuoso'] # Array of strings: Default tags will be set or appended to comments/posts

# Steemd Settings
primary_steemd_node: https://steemd.steemit.com
secondary_steemd_node: https://rpc.steemliberator.com
